/* SPDX-License-Identifier: GPL-3.0 */
#ifndef MODULE_CRC_BYPASS_H
#define MODULE_CRC_BYPASS_H

#define MODULE_CRC_BYPASS_VERSION "1.0.0"
#define MODULE_CRC_BYPASS_STATUS_SIZE 256

#endif /* MODULE_CRC_BYPASS_H */
